GET http://localhost:3001/user/ HTTP/1.1
# Content-Type: application/x-www-form-urlencoded
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NjA3YTUwOS02MmVhLTQ5ZmMtYmM1Yy02YTY5OTUzNmRkZmIiLCJpYXQiOjE2ODc1MTcwODAsImV4cCI6MTY4NzUzNTA4MCwidHlwZSI6ImFjY2VzcyJ9.yN1GmxWWLccGr2t3LGyxa69yLvskIVJeTIynSqotN3Y